# -*- coding: utf-8 -*-
"""numpy2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lL_wT_kQhRZty0mK32ydJnsqLDgtKzCO
"""

import numpy as np
print(np.info(np.add))



import numpy as np
print(np.__version__)

import tensorflow as tf
print(tf.__version__)

#wap a numpy program to test if any of the elments of a given array are non zero
import numpy as np
x=np.array([0,0,0,0])
print(np.any(x))
#print(np.all(x))

#wap to test elemets wise positive or negative infinty
import numpy as np
a=np.array([1,0,-2,np.inf,-np.inf,3.5])
print("Postive infinity:",np.isposinf(a))
print("negative infinity:",np.isneginf(a))

# wap to test element wise for nan(not anumber )of a given array
import numpy as np
a=np.array([1,0,np.nan,np.inf])
print("test element wise for nan:",np.isnan(a))

#wap to create an array of integer from 30-70 no need to use for for loop
import numpy as np
a=np.arange(30,71)
h=np.arange(30,71,2)
print(a)
print(h)

# wap to numpy program create a 3x3 identity matrix
import numpy as np
a=np.identity(3)
print(a)

# wap to perform addition,subtraction,multiplication of two matrix
import numpy as np
a=np.array([[5,8,9],[4,5,6]])
b=np.array([[4,6,8],[11,5,8]])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))

#wap to reverse 4x4 array
import numpy as np
a=np.arange(16,32)
print(a)
b=a.reshape(4,4)
print(b)
print(b[::-1])

#wap to transpose given 4x4 matrix
print(b.transpose())

#wap to create new array from given array from swapping 1st and last ,2nd and third
print(b)